// tb_conv1.v
// Loads a golden test sample's input image, runs the accelerator, and
// compares the resulting per-channel accumulator RAM contents against the
// golden_hex/conv1_acc_<N>.hex reference generated by quantize_and_golden.py.
//
// Usage (Icarus Verilog):
//   iverilog -o sim rtl/mac_unit.v rtl/conv1_controller.v rtl/conv1_mem.v \
//            rtl/top_conv1_accelerator.v tb/tb_conv1.v
//   vvp sim +SAMPLE=0
//
// NOTE (known open item for Day 5 verification pass): img_rom and
// wgt_rom_tapmajor are registered (1-cycle read latency). The controller's
// acc_clear currently asserts based on tap_idx==0 in the SAME cycle the
// address is presented, not the cycle the data arrives. Because both ROMs
// share identical latency this may resolve to a consistent one-cycle
// pipeline shift rather than a functional error -- but this must be
// confirmed against the golden vectors below, and a one-cycle enable/clear
// delay register added to conv1_controller if the comparison fails. This is
// exactly the kind of bug the Day 5 "verify against golden model" milestone
// exists to catch -- do not skip simulation before moving on to Conv2.

`timescale 1ns/1ps

module tb_conv1;
    reg clk = 0;
    reg rst_n = 0;
    reg start = 0;
    wire done;

    integer sample;
    reg [8*64:0] img_fname;
    integer errors;
    integer f;

    reg signed [31:0] golden_acc [0:3][0:35]; // [channel][pixel]
    integer ch, px;

    top_conv1_accelerator dut (
        .clk(clk), .rst_n(rst_n), .start(start), .done(done)
    );

    always #5 clk = ~clk;


    task load_golden(input integer s);
        integer c;
        reg [8*64:0] fname;
        reg [31:0] flat_mem [0:143]; // 4 channels x 36 pixels, channel-major
        begin
            $sformat(fname, "golden_hex/conv1_acc_%0d.hex", s);
            $readmemh(fname, flat_mem);
            for (c = 0; c < 4; c = c + 1)
                for (px = 0; px < 36; px = px + 1)
                    golden_acc[c][px] = flat_mem[c*36 + px];
        end
    endtask

    initial begin
        sample = 0;
        if ($value$plusargs("SAMPLE=%d", sample)) ;

        // re-point image ROM to the requested sample before reset releases
        $sformat(img_fname, "golden_hex/input_%0d.hex", sample);
        $readmemh(img_fname, dut.u_img_rom.mem);
        load_golden(sample);

        errors = 0;
        rst_n = 0; start = 0;
        #20 rst_n = 1;
        #10 start = 1;

        wait (done == 1);
        #10;

        // Bit-exact comparison: RTL out_acc_ram contents vs. golden model
        errors = 0;
        for (px = 0; px < 36; px = px + 1) begin
            if (dut.u_ram_ch0.mem[px] !== golden_acc[0][px]) begin
                $display("MISMATCH ch0 px%0d: rtl=%0d golden=%0d", px, dut.u_ram_ch0.mem[px], golden_acc[0][px]);
                errors = errors + 1;
            end
            if (dut.u_ram_ch1.mem[px] !== golden_acc[1][px]) begin
                $display("MISMATCH ch1 px%0d: rtl=%0d golden=%0d", px, dut.u_ram_ch1.mem[px], golden_acc[1][px]);
                errors = errors + 1;
            end
            if (dut.u_ram_ch2.mem[px] !== golden_acc[2][px]) begin
                $display("MISMATCH ch2 px%0d: rtl=%0d golden=%0d", px, dut.u_ram_ch2.mem[px], golden_acc[2][px]);
                errors = errors + 1;
            end
            if (dut.u_ram_ch3.mem[px] !== golden_acc[3][px]) begin
                $display("MISMATCH ch3 px%0d: rtl=%0d golden=%0d", px, dut.u_ram_ch3.mem[px], golden_acc[3][px]);
                errors = errors + 1;
            end
        end

        if (errors == 0)
            $display("SAMPLE %0d: PASS -- all 144 Conv1 accumulator values bit-exact match golden model", sample);
        else
            $display("SAMPLE %0d: FAIL -- %0d/144 mismatches", sample, errors);

        $finish;
    end

    

endmodule
